[workspace]
members = ["cli", "gui", "lib"]
resolver = "2"

[workspace.dependencies]
toposort-scc = "0.5"
byteorder = "1.5"
rust-ini = "0.20"
log = "0.4"
env_logger = "0.11"
regex = "1.10"
openmw-cfg = "0.5"                                              # move to feature flag
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2

[patch.crates-io]
