[package]
name = "plox"
description = "PLOX - ??? Load Order eXpert. PLOX is a tool for analyzing and sorting your plugin load order. Supports Morrowind and Cyberpunk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toposort-scc = "0.5"
clap = { version = "4.1", features = ["derive"] }
byteorder = "1.5"
rust-ini = "0.20"
log = "0.4"
env_logger = "0.11"
regex = "1.10"
openmw-cfg = "0.5"                                              # move to feature flag
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# standard crate data is left out
[dev-dependencies]
pretty_assertions = "1.3"
rand = "0.8"
