[package]
name = "cmop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toposort-scc = "0.5"
clap = { version = "4.1", features = ["derive"] }
byteorder = "1.5"

# standard crate data is left out
[dev-dependencies]
pretty_assertions = "1.3"
