[package]
name = "cmop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
topological-sort = "0.2.2"
clap = { version = "4.1.8",  features = ["derive"] }
