name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cmop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Check
      run: |
        cd cmop
        cargo check --all-features
    - name: Format
      run: |
        cd cmop
        cargo fmt --all -- --check   
    - name: Clippy
      run: |
        cd cmop
        cargo clippy -- -D warnings
      
    - name: Build
      run: |
        cd cmop
        cargo build --verbose
    - name: Run tests
      run: |
        cd cmop
        cargo test --verbose
