name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --release --verbose --all
      - name: Run tests
        run: cargo test --release --verbose --all

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plox-win
          path: target/release/plox.exe

  ci-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --release --verbose --all
      - name: Run tests
        run: cargo test --release --verbose --all

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plox-macos
          path: target/release/plox

  ci-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --release --verbose --all
      - name: Run tests
        run: cargo test --release --verbose --all

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plox-linux
          path: target/release/plox
